[package]
name = "wgpu-zoo"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
pollster = "0.3.0"
wgpu = "0.17.0"
winit = "0.28.6"
notify = "6.1.1"
glam = {version = "0.24.1", features = ["bytemuck"] }
